=== dy6P/TP-Dev-WEB/XML/Voiliers/voiliers.dtd
<!ELEMENT voiliers (mixte, voilier+)>
    <!ATTLIST voiliers
        transat CDATA #REQUIRED
    >
<!ELEMENT voilier (nom, photo, skipper, skipper)>
    <!ATTLIST voilier
        classe CDATA #REQUIRED
        annee CDATA #REQUIRED
    >
<!ELEMENT nom (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT skipper (origine, nom)>
    <!ATTLIST skipper
        age CDATA #REQUIRED
    >
<!ELEMENT origine (#PCDATA)>
<!ELEMENT geo (#PCDATA)>
<!ELEMENT cat (#PCDATA)>
<!ELEMENT mixte (#PCDATA | geo | cat)*>

=== dy6P/TP-Dev-WEB/XML/Voiliers/voiliers.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE voiliers SYSTEM "voiliers.dtd">
<voiliers transat="Café 2025">

    <mixte>Les 25 et 26 octobre 2025, soixante-quatorze voiliers ont pris le départ de la dix-septième édition de la Route du Café.
    Créée en 1993, cette course transatlantique en double relira cette année <geo>Le Havre</geo> à <geo>Fort-de-France</geo> en <geo>Martinique</geo>.
    Selon leur taille et leur configuration (monocoque ou multicoque), les voiliers seront répartis en quatre catégories :
    les <cat>Class40</cat>, les <cat>IMOCA</cat>, les <cat>Ocean Fifty</cat> et les <cat>Ultim</cat>.</mixte>

  <voilier classe="Class40" annee="2021">
    <nom>#EMPOWHER</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/empowher.jpg.webp?itok=Euo0m7Ve</photo>
    <skipper age="37">
      <origine>Dublin</origine>
      <nom>Pamela LEE</nom>
    </skipper>
    <skipper age="37">
      <origine>États-Unis d'Amérique</origine>
      <nom>Jay THOMPSON</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2022">
    <nom>11th Hour Racing</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/11TH%20HOUR%20RACING%20-%20Imoca.jpg.webp?itok=FtiSUJ_a</photo>
    <skipper age="37">
      <origine>Trieste</origine>
      <nom>Francesca CLAPCICH </nom>
    </skipper>
    <skipper age="31">
      <origine>Hampshire</origine>
      <nom> Will HARRIS</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2015">
    <nom>4CAD - LA MIE CÂLINE</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/4%20CAD%20-%20LA%20MIE%20CALINE%20-%20Imoca.jpg.webp?itok=70FnGUcH</photo>
    <skipper age="53">
      <origine> Les Sables d'Olonne</origine>
      <nom>Arnaud BOISSIÈRES</nom>
    </skipper>
    <skipper age="35">
      <origine>Les Sables d'Olonne</origine>
      <nom>Benjamin DUTREUX </nom>
    </skipper>
  </voilier>
  <voilier classe="Ultim" annee="2017">
    <nom>ACTUAL ULTIM 4</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/ACTUAL%20ULTIM%204%20%C2%A9Ronan_Gladu.jpg.webp?itok=iEu877I4</photo>
    <skipper age="40">
      <origine>Saint-Brieuc</origine>
      <nom>Anthony MARCHAND</nom>
    </skipper>
    <skipper age="38">
      <origine>Lorient</origine>
      <nom>Julien VILLION</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2019">
    <nom>AIRVANCE OCÉAN TERÉLIAN</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-10/AIRVANCE%20OC%C3%89LIAN%20TER%C3%89LIAN%20-%20Class40.jpg.webp?itok=HVxv8_z7</photo>
    <skipper age="26">
      <origine>calais</origine>
      <nom>Théa KHELIF</nom>
    </skipper>
    <skipper age="43">
      <origine>Havre</origine>
      <nom>Marion ENGELHARD</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2022">
    <nom>ALDERAN</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/alderan.jpg.webp?itok=1JaFi1pB</photo>
    <skipper age="32">
      <origine>Paris</origine>
      <nom>Sasha LANIECE</nom>
    </skipper>
    <skipper age="34">
      <origine>Kiel</origine>
      <nom>Sanni BEUCKE</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2023">
    <nom>ALLAGRANDE MAPEI</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-08/ALLAGRANDE%20MAPEI-Imoca.jpg.webp?itok=FypE7x1c</photo>
    <skipper age="34">
      <origine>Milan</origine>
      <nom>Ambrogio BECCARIA</nom>
    </skipper>
    <skipper age="44">
      <origine>Saint-Pol-sur-Mer</origine>
      <nom>Thomas RUYANT</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2023">
    <nom>ALTERNATIVE SAILING- LES CONSTRUCTIONS</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/alternative_sailing_-_les_constructions_de_belon.jpg.webp?itok=PYkuBV7v</photo>
    <skipper age="32">
      <origine>Brest</origine>
      <nom>Guillaume L'HOSTIS</nom>
    </skipper>
    <skipper age="40">
      <origine>Chartres</origine>
      <nom>Antoine LE MANCHEC</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2022">
    <nom>AMARRIS</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/amarris.jpg.webp?itok=TPlQAkao</photo>
    <skipper age="35">
      <origine>Montpellier</origine>
      <nom>Achille NEBOUT</nom>
    </skipper>
    <skipper age="50">
      <origine>Concarneau</origine>
      <nom>Gildas MAHÉ</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2025">
    <nom>ASSOCIATION PETITS PRINCES - QUEGUINER</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/ASSOCIATION%20PETITS%20PRINCES%20-%20QUEGUINER%20-%20Imoca%20-%20%C2%A9Romain%20mari.jpg.webp?itok=ynOlajzQ</photo>
    <skipper age="30">
      <origine>Morlaix</origine>
      <nom>Elodie BONAFOUS</nom>
    </skipper>
    <skipper age="51">
      <origine>Saint-Brieuc</origine>
      <nom>Yann ELIES</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2016">
    <nom>BELCO-CEC</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/cec_belco.jpg.webp?itok=QyvjClZA</photo>
    <skipper age="36">
      <origine>Beauvais</origine>
      <nom>Louis MAYAUD</nom>
    </skipper>
    <skipper age="43">
      <origine>Harfleu</origine>
      <nom>Alexandre BELLANGÉ</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2024">
    <nom>BLEU BLANC PLANETE LOCATION</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/bleu_blanc_planete_location.jpg.webp?itok=Vi1QCMTW</photo>
    <skipper age="37">
      <origine>Saint-Malo</origine>
      <nom>Quentin LE NABOUR</nom>
    </skipper>
    <skipper age="52">
      <origine>Neuilly-sur-Seine</origine>
      <nom>Thierry CHABAGNY</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2020">
    <nom>BUREAU VALLÉE</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/BUREAU%20VALL%C3%89E%20-%20IMOCA%20%40%20Benjamin%20Sellier_wind4production.com_.png.webp?itok=ML97VaFk</photo>
    <skipper age="40">
      <origine>Evry</origine>
      <nom>Louis BURTON</nom>
    </skipper>
    <skipper age="30">
      <origine>Saint Brieuc</origine>
      <nom>Clément COMMAGNAC</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2011">
    <nom>CAFÉ JOYEUX</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/CAFE%20JOYEUX%20-%20IMOCA.jpeg.webp?itok=ompeE8Fo</photo>
    <skipper age="34">
      <origine>Paris</origine>
      <nom>Nicolas D'ESTAIS</nom>
    </skipper>
    <skipper age="37">
      <origine>Zurich - Suisse</origine>
      <nom>Simon KOSTER</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2022">
    <nom>CENTRAKOR HIRSH</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-10/CENTRAKOR%20-%20class40.jpg.webp?itok=VOa9mD6x</photo>
    <skipper age="44">
      <origine>Hyeres</origine>
      <nom>Mikael MERGUI</nom>
    </skipper>
    <skipper age="Non référencé">
      <origine>Saint Vivien de Médoc</origine>
      <nom>Kéni PIPEROL</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2022">
    <nom>CHARAL</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2023-10/231015_mlr_charal_155.jpg.webp?itok=y-sfi3H_</photo>
    <skipper age="49">
      <origine>Landivisiau</origine>
      <nom>Jérémie BEYOU</nom>
    </skipper>
    <skipper age="38">
      <origine>Saint-Paul (La Réunion)</origine>
      <nom>Morgan LAGRAVIÈRE</nom>
    </skipper>
  </voilier>
  <voilier classe="Imoca" annee="2010">
    <nom>COUP DE POUCE</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/COUP%20DE%20POUCE%20-%20Imoca.jpg.webp?itok=dTtCLDKU</photo>
    <skipper age="58">
      <origine>Rouen</origine>
      <nom>Manuel COUSIN</nom>
    </skipper>
    <skipper age="44">
      <origine>BIARRITZ</origine>
      <nom>Jean-Baptiste DARAM</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2020">
    <nom>CROSSCALL</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/crosscall.jpg.webp?itok=kfXQqKpy</photo>
    <skipper age="42">
      <origine>SERVOZ</origine>
      <nom>Aurélien DUCROZ</nom>
    </skipper>
    <skipper age="42">
      <origine>Villeneuve Saint-Georges</origine>
      <nom>Jonathan CHODKIEWIEZ</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2022">
    <nom>DÉFI SOLIDAIRE AVEC ELLYE ET L'ARCHE</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-08/DEFI%20SOLIDAIRE%20AVEC%20ELLYE%20ET%20L%27ARCHE%20-%20Class40.jpg.webp?itok=DWVmQli6</photo>
    <skipper age="49">
      <origine>Granville</origine>
      <nom>Nicolas JOSSIER</nom>
    </skipper>
    <skipper age="38">
      <origine>Rouen</origine>
      <nom>Sophie FAGUET</nom>
    </skipper>
  </voilier>
  <voilier classe="Ocean Fifty" annee="2025">
    <nom>EDENRED 5</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/EDENRED-Ocean%20Fifty.JPG.webp?itok=8YErlYtU</photo>
    <skipper age="53">
      <origine>Plouharnel</origine>
      <nom>Emmanuel LE ROCH</nom>
    </skipper>
    <skipper age="23">
      <origine>Saint-Philibert</origine>
      <nom>Basile BOURGNON</nom>
    </skipper>
  </voilier>
  <voilier classe="Class40" annee="2025">
    <nom>EKINOX</nom>
