=== dy6P/TP-Dev-WEB/JavaScript/XML/Route_du_Cafe_2025.dtd
<!ELEMENT voiliers (classe+)>
    <!ATTLIST voiliers
            transat CDATA #REQUIRED
    >
<!ELEMENT classe (voilier+)>
    <!ATTLIST classe
            nom (#PCDATA)
    >
<!ELEMENT voilier (nom, photo, skipper, skipper)>
    <!ATTLIST voilier
            date_construction CDATA #REQUIRED
    >
<!ELEMENT nom (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT skipper (nom)>
    <!ATTLIST skipper
            age CDATA #REQUIRED
            origine CDATA #REQUIRED
    >

=== dy6P/TP-Dev-WEB/JavaScript/XML/Route_du_cafe_2025.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE voiliers SYSTEM "Route_du_Cafe_2025.dtd">
<voiliers transat="Café 2025">
  <classe nom="Class40">
    <voilier date_construction="2021">
      <nom>#EMPOWHER</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/empowher.jpg.webp?itok=Euo0m7Ve</photo>
      <skipper age="37" origine="Dublin">Pamela LEE</skipper>
      <skipper age="37" origine="Americain">Jay THOMPSON</skipper>
    </voilier>
    <voilier date_construction="2019">
      <nom>AIRVANCE OCÉLIAN TERÉLIAN</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-10/AIRVANCE%20OC%C3%89LIAN%20TER%C3%89LIAN%20-%20Class40.jpg.webp?itok=HVxv8_z7</photo>
      <skipper age="26" origine="Calais">Théa KHELIF</skipper>
      <skipper age="43" origine="Le Havre">Marion ENGELHARD</skipper>
    </voilier>
    <voilier date_construction="2022">
      <nom>ALDERAN</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/alderan.jpg.webp?itok=1JaFi1pB</photo>
      <skipper age="32" origine="Paris">Sasha LANIECE</skipper>
      <skipper age="34" origine="Kiel">Sanni BEUCKE</skipper>
    </voilier>
    <voilier date_construction="2023">
      <nom>ALTERNATIVE SAILING- LES CONSTRUCTIONS DU BELON</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/alternative_sailing_-_les_constructions_de_belon.jpg.webp?itok=PYkuBV7v</photo>
      <skipper age="32" origine="Brest">Guillaume L'HOSTIS</skipper>
      <skipper age="40" origine="Chartres">Antoine LE MANCHEC</skipper>
    </voilier>
    <voilier date_construction="2022">
      <nom>AMARRIS</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/amarris.jpg.webp?itok=TPlQAkao</photo>
      <skipper age="35" origine="Montpellier">Achille NEBOUT</skipper>
      <skipper age="50" origine="Concarneau">Gildas MAHÉ</skipper>
    </voilier>
    <voilier date_construction="2016">
      <nom>BELCO-CEC</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/cec_belco.jpg.webp?itok=QyvjClZA</photo>
      <skipper age="36" origine="Beauvais">Louis MAYAUD</skipper>
      <skipper age="43" origine="Harflleur">Alexandre BELLANGÉ</skipper>
    </voilier>
    <voilier date_construction="2024">
      <nom>BLEU BLANC PLANETE LOCATION</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/bleu_blanc_planete_location.jpg.webp?itok=Vi1QCMTW</photo>
      <skipper age="37" origine="Saint-Malo">Quentin LE NABOUR</skipper>
      <skipper age="53" origine="Neuilly-sur-Seine">Thierry CHABAGNY</skipper>
    </voilier>
    <voilier date_construction="2022">
      <nom>CENTRAKOR HIRSH</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-10/CENTRAKOR%20-%20class40.jpg.webp?itok=VOa9mD6x</photo>
      <skipper age="44" origine="Hyeres">Mikael MERGUI</skipper>
      <skipper age="NR" origine="Saint Vivien de Médoc">Kéni PIPEROL</skipper>
    </voilier>
    <voilier date_construction="2020">
      <nom>CROSSCALL</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/crosscall.jpg.webp?itok=kfXQqKpy</photo>
      <skipper age="43" origine="SERVOZ">Aurélien DUCROZ</skipper>
      <skipper age="42" origine="Villeneuve Saint-Georges">Jonathan CHODKIEWIEZ</skipper>
    </voilier>
    <voilier date_construction="2022">
      <nom>DÉFI SOLIDAIRE AVEC ELLYE ET L'ARCHE</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-08/DEFI%20SOLIDAIRE%20AVEC%20ELLYE%20ET%20L%27ARCHE%20-%20Class40.jpg.webp?itok=DWVmQli6</photo>
      <skipper age="49" origine="Granville">Nicolas JOSSIER</skipper>
      <skipper age="38" origine="Rouen">Sophie FAGUET</skipper>
    </voilier>
    <voilier date_construction="2025">
      <nom>EKINOX</nom>
      <photo>https://www.class40.com/modules/bateaux/image.php?img=211/2025211ekinoxsineaulshprologuevincentolivaud%2Ejpg</photo>
      <skipper age="55" origine="Argenteuil">Benoît SINEAU</skipper>
      <skipper age="33" origine="Milan">Alberto RIVA</skipper>
    </voilier>
    <voilier date_construction="2022">
      <nom>ENGIE - DESSINE-MOI LA HIGH-TECH</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/cap_pour_elles_avec_engie.jpg.webp?itok=VO6lvHxu</photo>
      <skipper age="31" origine="Palma de Mallorca">Aina BAUZA ROIG</skipper>
      <skipper age="35" origine="Saint-Renan">Axelle PILLAIN</skipper>
    </voilier>
    <voilier date_construction="2014">
      <nom>ESATCO</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/ESATCO%20-%20Class40.jpeg.webp?itok=m_bFqoGQ</photo>
      <skipper age="42" origine="Nantes">Nicolas GUIBAL</skipper>
      <skipper age="24" origine="Corée du Sud">Gauthier BRIL</skipper>
    </voilier>
    <voilier date_construction="2023">
      <nom>INFLUENCE2</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/INFLUENCE2-Class40.jpg.webp?itok=VJ2QHLkG</photo>
      <skipper age="48" origine="Rome">Andrea FORNARO</skipper>
      <skipper age="33" origine="Rome">Alessandro TORRESANI</skipper>
    </voilier>
    <voilier date_construction="2021">
      <nom>INLAND ROOTS OCEAN SOUL</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/inland_roots_ocean_soul.jpg.webp?itok=YokotH2W</photo>
      <skipper age="48" origine="Louny">Milan KOLACEK</skipper>
      <skipper age="44" origine="Amiens">Pierre BRASSEUR</skipper>
    </voilier>
    <voilier date_construction="2011">
      <nom>INNOVAD.GROUP - XLG</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/INNOVAD.GROUP%20-%20XLG%20-%20Class40.jpg.webp?itok=QNNnhSc4</photo>
      <skipper age="40" origine="Anderlecht">Jérôme DELIRE</skipper>
      <skipper age="38" origine="Uccle">Caroline DIEU</skipper>
    </voilier>
    <voilier date_construction="2020">
      <nom>INTERACTION</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/interaction.jpg.webp?itok=P3vGyCpn</photo>
      <skipper age="59" origine="Arcachon">Yannig LIVORY</skipper>
      <skipper age="56" origine="Arcachon">Erwan LIVORY</skipper>
    </voilier>
    <voilier date_construction="2018">
      <nom>L'AGENCE TELECOM - SOTRAPLANT</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/l_agence_telecom_-_sotraplant.png.webp?itok=TpV_hm5B</photo>
      <skipper age="52" origine="Montpellier">Matthieu FOULQUIER-GAZAGNES</skipper>
      <skipper age="24" origine="Nice">Gildas BEAUCHAMPS</skipper>
    </voilier>
    <voilier date_construction="2023">
      <nom>LEGALLAIS</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/legallais.jpg.webp?itok=PZpSr1YI</photo>
      <skipper age="41" origine="Larmor Plage">Fabien DELAHAYE</skipper>
      <skipper age="45" origine="Nantes">Pierre LEBOUCHER</skipper>
    </voilier>
    <voilier date_construction="2024">
      <nom>LES INVINCIBLES</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/LES%20INVINCIBLES%20-%20Class40.jpg.webp?itok=agFVeXD5</photo>
      <skipper age="32" origine="Paris">William MATHELIN-MOREAUX</skipper>
      <skipper age="40" origine="Venise">Pietro LUCIANI</skipper>
    </voilier>
    <voilier date_construction="2025">
      <nom>MACCAFERRI FUTURA</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/MACCAFERRI%20FUTURA%20-%20Class40.jpg.webp?itok=a6jXdbTx</photo>
      <skipper age="30" origine="Bologne">Luca ROSETTI</skipper>
      <skipper age="28" origine="Genova ">Matteo SERICANO</skipper>
    </voilier>
    <voilier date_construction="2012">
      <nom>MARTINIQUE HORIZON</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-08/MARTINIQUE%20HORIZON%20-%20CLASS40.jpg.webp?itok=6tHUoQtS</photo>
      <skipper age="40" origine="Sainte-Luce">Jean-Yves AGLAE</skipper>
      <skipper age="37" origine="Le Lamentin">Moane MANGATTALE</skipper>
    </voilier>
    <voilier date_construction="2023">
      <nom>NST RACING &amp; CABINET Z</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/NST%20RACING%20%26%20CABINET%20Z%20-%20Class40.jpg.webp?itok=rmQzHSkK</photo>
      <skipper age="25" origine="Brest ">Thomas JOURDREN</skipper>
      <skipper age="26" origine="France">Joseph CLOAREC</skipper>
    </voilier>
    <voilier date_construction="2022">
      <nom>OCEAN CONNECT - THE SEA CLEANERS</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-10/THE%20SEA%20CLEANERS%20-%20Class40.jpg.webp?itok=20BOFp2V</photo>
      <skipper age="36" origine="Rochefort">Jean Baptiste TERNON</skipper>
      <skipper age="38" origine="Lorient ">Gaëtan THOMAS</skipper>
    </voilier>
    <voilier date_construction="2010">
      <nom>OSE TA VICTOIRE</nom>
      <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/ose_ta_victoire.jpeg.webp?itok=MzYwc4KP</photo>
      <skipper age="28" origine="Vannes">Thomas LURTON</skipper>
      <skipper age="26" origine="Uccle">Sacha VANDENBROUCK</skipper>
    </voilier>
    <voilier date_construction="2014">
      <nom>PHARE 40 - HA PLUS PME</nom>
